#!/bin/bash
set -x

$CMAKE \
	-DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE \
	-DCMAKE_BUILD_TYPE:String=$BUILD_TYPE \
	-DANDROID_STL:STRING=c++_shared \
	-DANDROID_SDK:PATH=$ANDROID_SDK_ROOT \
	-DCMAKE_SYSTEM_NAME=Android \
	-DANDROID_NDK=$ANDROID_NDK_ROOT \
	-DANDROID_PLATFORM=android-$API \
	-DANDROID_ABI:STRING=$ABI \
	-DANDROID_TOOLCHAIN=clang \
	-DANDROID_SDK_BUILD_TOOLS_REVISION=$ANDROID_SDK_BUILD_TOOLS\
	-DCMAKE_FIND_ROOT_PATH:PATH=${QT_INSTALL_PREFIX} \
	-DCMAKE_LIBRARY_PATH=$DEV_PREFIX \
	-DCMAKE_INSTALL_PREFIX=$DEV_PREFIX \
	-DCMAKE_STAGING_PREFIX=$DEV_PREFIX \
	-DCMAKE_C_FLAGS="${C_FLAGS}" \
	-DCMAKE_CPP_FLAGS="${CPP_FLAGS}" \
	-DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS_COMMON}" \
	-DCMAKE_SHARED_LINKER_FLAGS="${LDFLAGS_COMMON}" \
	-DANDROID_ARM_NEON=ON \
	-DANDROID_LD=lld \
	-DQt5_DIR=${QT_INSTALL_PREFIX}/lib/cmake/Qt5 \
	-DQt5Widgets_DIR=${QT_INSTALL_PREFIX}/lib/cmake/Qt5Widgets \
	-DQt5Gui_DIR=${QT_INSTALL_PREFIX}/lib/cmake/Qt5Gui \
	-DQt5Core_DIR=${QT_INSTALL_PREFIX}/lib/cmake/Qt5Core \
	-DQT_INSTALL_PREFIX=${QT_INSTALL_PREFIX} \
	-DQT_QMAKE_EXECUTABLE:STRING=${QMAKE} \
	-DCMAKE_PREFIX_PATH:STRING=${QT_INSTALL_PREFIX}/lib/cmake\;${DEV_PREFIX}/lib/cmake\
	-DCMAKE_C_COMPILER:STRING=$CC \
	-DCMAKE_CXX_COMPILER:STRING=$CXX \
	-DANDROID_NATIVE_API_LEVEL:STRING=$API \
	-B${BUILDDIR} \
	$@
